---
# --- Variables --- #

repo     : "snowplow-generic"
user_org : "snowplow"

versions:
  scala_stream_collector     : "0.9.0"
  stream_enrich              : "0.10.0"
  kinesis_elasticsearch_sink : "0.8.0"

binary_paths:
  scala_stream_collector     : "2-collectors/scala-stream-collector/target/scala-2.10/snowplow-stream-collector"
  stream_enrich              : "3-enrich/stream-enrich/target/scala-2.10/snowplow-stream-enrich"
  kinesis_elasticsearch_sink : "4-storage/kinesis-elasticsearch-sink/target/scala-2.10/snowplow-elasticsearch-sink"

sbt_version_cmd : sbt version -Dsbt.log.noformat=true | awk 'END{print}' | sed -r 's/\[info\]\s(.*)/\1/' | xargs echo -n

# --- Release Manager Config --- #

local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

targets:
  - type     : "bintray"
    user     : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_USER'] %>
    password : <%= ENV['BINTRAY_SNOWPLOW_GENERIC_API_KEY'] %>

packages:
  - repo     : "{{ repo }}"
    name     : "snowplow"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: false
    version  : <%= CMD['echo `cat VERSION` | xargs echo -n'] %>
    build_version : <%= ENV['TRAVIS_BUILD_RELEASE_TAG'] %>
    build_commands:
      - cd 3-enrich/scala-common-enrich && sbt +publishLocal && cd ../..
      - cd 2-collectors/scala-stream-collector && sbt assembly
      - cd 3-enrich/stream-enrich && sbt assembly
      - cd 4-storage/kinesis-elasticsearch-sink && export ELASTICSEARCH_VERSION=1x && sbt assembly
      - cd 4-storage/kinesis-elasticsearch-sink && export ELASTICSEARCH_VERSION=2x && sbt assembly
    artifacts:
      - prefix : "snowplow_kinesis_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.scala_stream_collector }}-{{ versions.scala_stream_collector }}"
          - "{{ binary_paths.stream_enrich }}-{{ versions.stream_enrich }}"
          - "{{ binary_paths.kinesis_elasticsearch_sink }}-{{ versions.kinesis_elasticsearch_sink }}-1x"
          - "{{ binary_paths.kinesis_elasticsearch_sink }}-{{ versions.kinesis_elasticsearch_sink }}-2x"

  - repo     : "{{ repo }}"
    name     : "snowplow-scala-stream-collector"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: true
    version  : "{{ versions.scala_stream_collector }}"
    build_version : "{{ versions.scala_stream_collector }}"
    artifacts:
      - prefix : "snowplow_scala_stream_collector_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.scala_stream_collector }}-{{ versions.scala_stream_collector }}"

  - repo     : "{{ repo }}"
    name     : "snowplow-stream-enrich"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: true
    version  : "{{ versions.stream_enrich }}"
    build_version : "{{ versions.stream_enrich }}"
    artifacts:
      - prefix : "snowplow_stream_enrich_"
        suffix : ""
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.stream_enrich }}-{{ versions.stream_enrich }}"

  - repo     : "{{ repo }}"
    name     : "snowplow-kinesis-elasticsearch-sink"
    user_org : "{{ user_org }}"
    publish  : true
    override : false
    continue_on_conflict: true
    version  : "{{ versions.kinesis_elasticsearch_sink }}"
    build_version : "{{ versions.kinesis_elasticsearch_sink }}"
    artifacts:
      - prefix : "snowplow_kinesis_elasticsearch_sink_"
        suffix : "_1x"
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.kinesis_elasticsearch_sink }}-{{ versions.kinesis_elasticsearch_sink }}-1x"
      - prefix : "snowplow_kinesis_elasticsearch_sink_"
        suffix : "_2x"
        type   : "zip"
        binary_paths:
          - "{{ binary_paths.kinesis_elasticsearch_sink }}-{{ versions.kinesis_elasticsearch_sink }}-2x"
